service: mpd-backend

provider:
  name: aws
  runtime: python3.7
  region: eu-central-1


custom:
  siteName: farmatic.com
  s3Sync:
    - bucketName: ${self:custom.siteName}
      localDir: ../Frontend/build/
      params:
        - "*":
            CacheControl: 'max-age=30'

resources:
  Resources:
    StaticSite:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:custom.siteName}
        WebsiteConfiguration:
          IndexDocument: index.html
    StaticSiteS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: StaticSite
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
              - s3:GetObject
              Resource:
                Fn::Join: [
                  "", [
                    "arn:aws:s3:::",
                    {
                      "Ref": "StaticSite"
                    },
                    "/*"
                  ]
                ]

plugins:
  - serverless-s3-sync
